# Generated by Django 4.2.2 on 2023-06-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blub",
            name="status",
        ),
    ]
