# Generated by Django 4.2.2 on 2023-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_bulb_classroom_delete_blub_delete_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="color",
            field=models.IntegerField(default=2.2),
            preserve_default=False,
        ),
    ]
