# Generated by Django 4.2.2 on 2023-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="color",
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
